---
driver:
  name: docker

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-6.8
    driver_config: 
      image: codespaces/chef-node-centos-6
      forward: 
        - 8080:8080
        
suites:
  - name: default
    run_list:
      - recipe[java::install]
      - recipe[tomcat::install]
      - recipe[tomcat::service]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
